# **ANALISIS EXPLORATORIO INICIAL**

- ALUMNO: DIEGO CESAR LARICO CRUZ - 20212679A

**NOTA**: Cargar el csv dentro de los archivos del colab para ejecutar el EDA sin problemas

In [1]:
import pandas as pd

# Cargar el dataset
df = pd.read_csv('Datos_abiertos_cepre_2024_1_2025_1.csv')

In [2]:
df.head()

,IDHASH,COLEGIO,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,COLEGIO_PAIS,COLEGIO_ANIO_EGRESO,ESPECIALIDAD,ANIO_POSTULA,CICLO_POSTULA,...,ANIO_NACIMIENTO,NACIMIENTO_PAIS,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,CALIF_FINAL,INGRESO,MODO_INGRESO,FECHA_CORTE
0,BE11517F469351A6FA152F8AD70F9707812804B0112D18...,cristian huygens,LIMA,LIMA,SAN JUAN DE LURIGANCHO,PERU,2021,SIN ESPECIALIDAD,2024,1,...,2004,Brazil,SIN DATO,SIN DATO,SIN DATO,MASCULINO,12.500,NO,SIN INGRESO,20250630
1,5519D203EC72BC2D14DEB410AFEB66E22C5E135A9232AB...,COLEGIO EL COMERCIO 32,PUNO,SAN ROMAN,JULIACA,PERU,1997,SIN ESPECIALIDAD,2024,1,...,1980,Peru,PUNO,SAN ROMAN,JULIACA,FEMENINO,0.168,NO,SIN INGRESO,20250630
2,FB5D70645AC934046646CDD8BD162714E324A8E444E5EE...,I E Manuel Scorza Torres,LIMA,LIMA,INDEPENDENCIA,PERU,2003,SIN ESPECIALIDAD,2024,1,...,1984,Peru,LIMA,LIMA,INDEPENDENCIA,MASCULINO,0.188,NO,SIN INGRESO,20250630
3,063276C4ED0A1A0115AC54FACFD30F3DA43DD686E311B7...,RICARDO BENTIN,LIMA,LIMA,RIMAC,PERU,2003,SIN ESPECIALIDAD,2024,1,...,1987,Peru,LIMA,LIMA,LIMA,MASCULINO,7.746,NO,SIN INGRESO,20250630
4,49275FD4C1059A9D9EA42C7C8FA4C86F1357E6BF428779...,Trilce,LIMA,LIMA,JESUS MARIA,PERU,2005,INGENIERÍA DE MINAS,2024,1,...,1989,Peru,LIMA,LIMA,LIMA,MASCULINO,11.544,SI,ORDINARIO,20250630

In [8]:
#dimensiones del dataframe
df.shape

(8470, 23)

In [3]:
# Verificamos las variables
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8470 entries, 0 to 8469
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   IDHASH               8470 non-null   object
 1   COLEGIO              8470 non-null   object
 2   COLEGIO_DEPA         8470 non-null   object
 3   COLEGIO_PROV         8470 non-null   object
 4   COLEGIO_DIST         8470 non-null   object
 5   COLEGIO_PAIS         8470 non-null   object
 6   COLEGIO_ANIO_EGRESO  8470 non-null   int64
 7   ESPECIALIDAD         8470 non-null   object
 8   ANIO_POSTULA         8470 non-null   int64
 9   CICLO_POSTULA        8470 non-null   int64
 10  DOMICILIO_DEPA       8470 non-null   object
 11  DOMICILIO_PROV       8470 non-null   object
 12  DOMICILIO_DIST       8470 non-null   object
 13  ANIO_NACIMIENTO      8470 non-null   int64
 14  NACIMIENTO_PAIS      8470 non-null   object
 15  NACIMIENTO_DEPA      8470 non-null   object
 16  NACIMIENTO_PROV      8470 non-null   object
 17  NACIMIENTO_DIST      8470 non-null   object
 18  SEXO                 8470 non-null   object
 19  CALIF_FINAL          8470 non-null   float64
 20  INGRESO              8470 non-null   object
 21  MODO_INGRESO         8470 non-null   object
 22  FECHA_CORTE          8470 non-null   int64
dtypes: float64(1), int64(5), object(17)
memory usage: 1.5+ MB

Conclusiones hasta este punto:
- No hay valores nulos
- Se debe renombrar las variables

Ahora evaluamos las variables

In [9]:
#variables categoricas

print(df.describe(include=['O']))

                                                   IDHASH        COLEGIO  \
count                                                8470           8470
unique                                               5808           4614
top     AE1C391A973804E2AAE891DAD46D7B56A784223D2285F1...  Saco Oliveros
freq                                                    3            312

       COLEGIO_DEPA COLEGIO_PROV COLEGIO_DIST COLEGIO_PAIS      ESPECIALIDAD  \
count          8470         8470         8470         8470              8470
unique           25          141          364            1                32
top            LIMA         LIMA         LIMA         PERU  SIN ESPECIALIDAD
freq           6391         6114          837         8470              6902

       DOMICILIO_DEPA DOMICILIO_PROV DOMICILIO_DIST NACIMIENTO_PAIS  \
count            8470           8470           8470            8470
unique             22             98            238              12
top              LIMA           LIMA           LIMA            Peru
freq             7200           6993           1937            8434

       NACIMIENTO_DEPA NACIMIENTO_PROV NACIMIENTO_DIST       SEXO INGRESO  \
count             8470            8470            8470       8470    8470
unique              26             153             452          2       2
top               LIMA            LIMA            LIMA  MASCULINO      NO
freq              5976            5718            1382       6456    6903

       MODO_INGRESO
count          8470
unique            3
top     SIN INGRESO
freq           6903

- FECHA_CORTE no es significativo
- COLEGIO_PAIS no es significativo, todos son de PERU

In [16]:
cols = ['CICLO_POSTULA', 'ANIO_POSTULA', 'MODO_INGRESO', 'INGRESO', 'SEXO']

for col in cols:
    print(f"\n Valores únicos: {col}")
    print(df[col].unique())

 Valores únicos: CICLO_POSTULA
[1 2]

 Valores únicos: ANIO_POSTULA
[2024 2025]

 Valores únicos: MODO_INGRESO
['SIN INGRESO' 'ORDINARIO' 'DIRECTO']

 Valores únicos: INGRESO
['NO' 'SI']

 Valores únicos: SEXO
['MASCULINO' 'FEMENINO']

In [11]:
# Variables numericas
print(df.describe())

       COLEGIO_ANIO_EGRESO  ANIO_POSTULA  CICLO_POSTULA  ANIO_NACIMIENTO  \
count          8470.000000   8470.000000    8470.000000      8470.000000
mean           2021.537190   2024.316057       1.368359      2004.839315
std               1.897783      0.464963       0.482388        21.804145
min            1997.000000   2024.000000       1.000000         6.000000
25%            2021.000000   2024.000000       1.000000      2004.000000
50%            2022.000000   2024.000000       1.000000      2005.000000
75%            2023.000000   2025.000000       2.000000      2006.000000
max            2024.000000   2025.000000       2.000000      2009.000000

       CALIF_FINAL  FECHA_CORTE
count  8470.000000       8470.0
mean      7.412488   20250630.0
std       4.141927          0.0
min       0.000000   20250630.0
25%       3.960250   20250630.0
50%       7.524000   20250630.0
75%      10.832750   20250630.0
max      17.343000   20250630.0

In [12]:
# Muestra los valores únicos de la columna 'MODO_INGRESO'
df['MODO_INGRESO'].unique()

array(['SIN INGRESO', 'ORDINARIO', 'DIRECTO'], dtype=object)

In [13]:
# Muestra los valores únicos de la columna 'CICLO_POSTULA'
df['CICLO_POSTULA'].unique()

array([1, 2])

In [14]:
df['FECHA_CORTE'].unique()

array([20250630])

In [17]:
df['ANIO_POSTULA'].unique()

array([2024, 2025])

In [18]:
pd.crosstab(df['CICLO_POSTULA'], df['ANIO_POSTULA'])

ANIO_POSTULA   2024  2025
CICLO_POSTULA
1              2673  2677
2              3120     0

Tenemos los siguientes resultados
- Postulantes 24-1: 2673
- Postulantes 24-2: 3120
- Postulantes 25-1: 2677